cc_library(
    name = "fifo_lib",
    deps = ["//ara/com:com_error_domain","//ara/core:instance_specifier",],
    hdrs = ["fifo_skeleton.h","fifo_proxy.h"],
    visibility = ["//visibility:public"],
)