cc_library(
    name = "ntp_config_manager",
    srcs = [
        "config_manager.cpp",
    ],
    hdrs = [
        "config_manager.hpp",
    ],
    deps = [
        "//core/json:simba_json",
        "@srp_platform//ara/log",
    ],
    visibility = ["//visibility:public"],
)