cc_library(
    name = "csvdriver",
    deps = [
    "//core/common:common_types",
    "//core/logger:Logger",
    ],
    srcs = ["csvdriver.cc"],
    hdrs = [
        "csvdriver.h",
        "Icsvdriver.h",
        ],
    visibility = ["//apps/logger_service:__subpackages__"],
)