cc_library(
    name = "sd_controller",
    srcs = ["sd_controller.cc"],
    hdrs = ["sd_controller.h"],
    visibility = ["//platform/common/someip_demon/code:__subpackages__"],
    deps = [
        "//platform/common/someip_demon/code/common:controller",
        "//platform/common/someip_demon/code/common/com:interface",
        "//platform/common/someip_demon/code/db",
        "//core/common:condition_lib",
        "//ara/com/someip:someip_data",
        "//ara/log",
    ],
)
