
cc_library(
    name = "diag_exec_factories",
    deps = [
        "//diag/exec/data:diag_exec_header"
    ],
    srcs = ["exec_msg_factory.cpp"],
    hdrs = ["exec_msg_factory.hpp"],
    visibility = ["//visibility:public"],
)
