cc_test(
    name = "csv_test",
    srcs = ["csv_test.cc"],
    deps = [
        "//core/csvdriver",
        "@com_google_googletest//:gtest_main",
        "//core/file:mock_file",
    ],
    size = "medium",
)
