cc_test(
    name = "benchmarks",
    srcs = ["result_benchmark.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//ara/core:Result",
        "@com_google_benchmark//:benchmark_main",
    ],
)
