cc_library(
    name = "rocket_state_base",
    srcs = ["rocket_state.cpp"],
    hdrs = ["rocket_state.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@srp_platform//ara/log",
    ],
)
