cc_library(
    name = "adaptive_application_lib",
    srcs = [
        "adaptive_lifecycle_menager.cc",
    ],
    hdrs = [
        "adaptive_application.h",
        "adaptive_lifecycle.h",
        "adaptive_lifecycle_menager.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ara/core:ara_initialization_lib",
        "//ara/core:instance_specifier",
        "//ara/log",
        "//ara/com",
    ],
)
