cc_library(
    name = "mock_application",
    hdrs = [
        "mock_IApplication.hpp"
        ],
    visibility = ["//visibility:public"],
    deps=[
        "@com_google_googletest//:gtest_main",
        "//core/application:application",
    ]
)