cc_binary(
    name = "mw_dtc_service",
    deps = [
        "//mw/diag/dtc/service:dtc_service_lib",
        ],
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
    data = ["//mw/diag/dtc:config.json"],
)