
cc_library(
    name = "dtc_msg_factory",
    deps = [
        "//communication-core/network-data:network_data_structure"
        ],
    srcs = ["dtc_msg_factory.cpp"],
    hdrs = ["dtc_msg_factory.hpp"],
    visibility = ["//srp/mw/dtc:__subpackages__"],
)

cc_library(
    name = "dtc_header",
    deps = [
        "//communication-core/network-data:network_data_structure"
        ],
    srcs = ["dtc_header.cpp"],
    hdrs = ["dtc_header.hpp"],
    visibility = ["//srp/mw/dtc:__subpackages__"],
)