filegroup(
    name = "resource",
    srcs = [
        "app_diag.json",
        "app_diag_f1.json",
        "app_diag_f2.json",
    ],
    visibility = ["//diag/config_controller/test:__subpackages__"],
)
