cc_library(
    name = "db",
    hdrs = [
        "database.h",
        "find_service_item.h",
        "service_item.h",
    ],
    visibility = ["//platform/common/someip_demon/code:__subpackages__"],
)
