cc_library(
    name = "diag_data_factory",
    srcs = ["diag_data_factory.cc"],
    hdrs = ["diag_data_factory.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/results:results_lib",
        "//diag/base/data:diag_data_structure",
    ],
)
