cc_library(
    name = "mock_gpio_controller",
    srcs = [
        "mock_gpio_controller.h",
        ],
    visibility = ["//visibility:public"],
    deps=[
        "@com_google_googletest//:gtest_main",
        "//mw/gpio_server/controller:gpio_controller",
    ],
    testonly = True,
)
