cc_test(
    name = "gpio_driver_test",
    srcs = ["test_gpio_driver.cpp"],
    deps = [
        "//core/gpio:gpio_drivers",
        "//core/file:mock_file",
        "@com_google_googletest//:gtest_main",
    ],
)