cc_library(
    name = "common_types",
    hdrs = ["error_code.h"],
    visibility = ["//core:__subpackages__"],
)

cc_library(
    name = "common_converter",
    hdrs = ["endianess_converter.h"],
    visibility = ["//core:__subpackages__"],
)