cc_library(
    name = "pd33x_driver",
    deps = [
        "//core/pd-33x/modbus:modbus_driver",
    ],
    srcs = ["pd33x.cpp"],
    hdrs = ["pd33x.hpp"],
    visibility = ["//visibility:public"],
)