cc_library(
    name = "simba_json",
    hdrs = [
        "json_parser.h",
    ],
    srcs = [
#        "json_parser.cc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@simdjson//:json",
    ],
)
