cc_library(
    name = "simba_json",
    srcs = ["json_parser.cc"],
    hdrs = ["json_parser.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_json//:json",
    ],
)


cc_library(
    name = "simdjson_json",
    srcs = ["simdjson_parser.cc"],
    hdrs = ["simdjson_parser.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@simdjson//:simdjson",
    ],
)

