cc_library(
    name = "simba_json",
    srcs = ["json_parser.cc"],
    hdrs = ["json_parser.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/results:results_lib",
        "@com_json//:json",
    ],
)
