# cc_library(
#     name = "job_common_lib",
#     srcs = ["job_common.cc"],
#     hdrs = [
#         "diag_request.h",
#         "diag_response.h",
#         "job_common.h",
#     ],
#     deprecation = "Please use: @srp_platform//ara/diag:uds_lib",
#     visibility = [
#         "//diag/jobs:__subpackages__",
#         "//diag/jobs/skeleton:__subpackages__"
#     ],
#     deps = [
#         "@srp_platform//ara/core:model_db_lib",
#         "@srp_platform//ara/log",
#         "//communication-core/sockets:socket_ipc",
#     ],
# )
