# cc_library(
#     name = "job_common_lib",
#     srcs = ["job_common.cc"],
#     hdrs = [
#         "diag_request.h",
#         "diag_response.h",
#         "job_common.h",
#     ],
#     deprecation = "Please use: //ara/diag:uds_lib",
#     visibility = ["//diag/jobs:__subpackages__"],
#     deps = [
#         "//ara/core:model_db_lib",
#         "//ara/log",
#         "//communication-core/sockets:socket_ipc",
#     ],
# )
