cc_library(
    name = "servoController",
    deps = [
        "//core/common:common_types",
        "//communication-core/sockets:socket_ipc",
    ],
    srcs = ["servoController.cpp"],
    hdrs = ["IservoController.hpp",
            "servoController.hpp"
            ],
)