cc_library(
    name = "logger_data_type_lib",
    srcs = ["data_type.cpp"],
    hdrs = ["data_type.hpp"],
    visibility = [
        "//apps/logger_service:__subpackages__",
        "//apps/logger_service/tests:__subpackages__"],
)