cc_library(
    name = "global_timestamp_controller",
    deps = [
        "//ara/com/shm:shm_lib",
    ],
    hdrs = [
        "global_timestamp.hpp",
    ],
    srcs = [
        "global_timestamp.cpp",
    ],
    visibility = ["//visibility:public"],
)