cc_library(
    name = "system_status",
    deps = [
        "@srp_platform//ara/log",
    ],
    srcs = ["system_stat.cpp"],
    hdrs = ["system_stat.hpp"],
    visibility = ["//visibility:public"],
)