cc_binary(
    name = "logger",
    srcs = [
        "main.cc",
    ],
    visibility = ["//deployment/platform/logger:__pkg__"],
    deps = [
        "//deployment/platform/logger:ara",
        "//platform/common/logger/code/application:dlt_service_lib",
    ],
)
