cc_test(
    name = "structure_test",
    srcs = ["header_structure_test.cc"],
    deps = [
        "//ara/com/someip:someip_lib",
        "@com_google_googletest//:gtest_main",
    ],
    size = "medium",
)
