# filegroup(
#     name = "config",
#     srcs = [
#         "platform_config.json",
#         "//deployment/cpu/pc/app:app_config",
#     ],
#     visibility = ["//deployment/cpu:__subpackages__"],
# )
