cc_library(
    name = "JsonParser",
    srcs = ["json_parser.cc"],
    hdrs = ["database_json_parser.h", "Ijson_parser.h", "json_parser.h"],
    deps = [
        "//communication-core/database:DatabaseLib",
        "@com_json//:json",
    ],
)
