name: 'Submodule Notify Parent'

on:
  push:
    branches:
      - master    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   call-workflow-passing-data:
    uses: Simba-Avionic/srp/.github/workflows/main.yml@dev
    secrets: inherit
