cc_library(
    name = "diag_dtc_data_structure",
    srcs = ["dtc_header.cpp"],
    hdrs = ["dtc_header.hpp"],
    deps=[
        "//communication-core/network-data:network_data_structure",
        "//communication-core/network-data:network_data_type",
    ],
    visibility = ["//visibility:public"],
)
