cc_library(
    name = "diag_msg_factory",
    srcs = ["diag_msg_factory.cc"],
    hdrs = ["diag_msg_factory.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/results:results_lib",
        "//diag/data:diag_data_structure",
    ],
)
