cc_library(
    name = "refuel_controller",
    deps = [
        "@srp_platform//ara/log",
    ],
    srcs = ["refuel_controller.cpp"],
    hdrs = ["refuel_controller.hpp"],
    visibility = ["//visibility:public"],
)