cc_test(
    name = "data_type_test",
    srcs = ["data_type_test.cc"],
    deps = [
        "//apps/ec/logger_service:logger_data_type_lib",
        "@com_google_googletest//:gtest_main",
    ],
    size = "medium",
)
