
cc_library(
    name = "servo_hdr",
    srcs = [
        "servo_hdr.cpp",
        ],
    hdrs = [
        "servo_hdr.hpp",
        ],
    deps = [
        "//communication-core/network-data:network_data_structure",
        "//communication-core/network-data:network_data_type",
    ],
    visibility = [
        "//mw/i2c_service/servo:__subpackages__",
        ],
)