load("@srp_platform//tools/model_generator/ara:data_structure_generator.bzl", "data_structure_generator")

data_structure_generator(
    name = "temp_com_data",
    model = [
        "//deployment/system_definition/platform/data_structure:temp_data_structure",
    ],
    visibility = ["//visibility:public"],
)