cc_library(
    name = "delta_pressure_driver",
    deps = [
        "//mw/gpio_server/controller:gpio_controller",
        "//core/uart:uart_driver",
    ],
    srcs = ["pd33x.cpp"],
    hdrs = ["pd33x.hpp"],
    visibility = ["//visibility:public"],
)