cc_library(
    name = "com_error_domain",
    srcs = ["com_error_domain.cc"],
    hdrs = [
        "com_error_domain.h",
        "type_converter.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//ara/core:error_lib"],
)

cc_library(
    name = "com_log",
    deps = ["//ara/log"],
    hdrs = ["log.h"],
    visibility = ["//ara/com:__subpackages__"],

)