cc_library(
    name = "com_error_domain",
    deps = ["//ara/core:error_lib"],
    srcs = ["com_error_domain.cc"],
    hdrs = ["com_error_domain.h"],
    visibility = ["//ara/com:__subpackages__"],
)