filegroup(
    name = "gpio_test_data",
    srcs = [
        "t1.json",
        "t2.json",
        "t3.json",
        "t4.json",
        "t5.json",
        "t6.json",
        ],
    visibility = ["//visibility:public"],
)