cc_library(
    name = "ipc_socket",
    srcs = ["proccess_socket.cc"],
    hdrs = ["proccess_socket.h"],
    data = [],
    visibility = ["//visibility:public"],
    deps = [
        "//ara/com:com_error_domain",
        "//ara/core:Result",
    ],
)
