cc_test(
    name = "nmea_test",
    srcs = [
        "nmea_tests.cc"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//core/gps:gps_data_parser",
    ],
)