cc_library(
    name = "mock_temp_driver",
    hdrs = ["mock_temp_driver.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//core/temp:temp_interface",
    ],
)
