cc_library(
    name = "proxy",
    srcs = [
        "event.h",
        "proxy.h",
    ],
    visibility = ["//ara/com:__subpackages__"],
    deps = [
        "//ara/com:types",
        "//ara/core:instance_specifier",
    ],
)
