

cc_library(
    name = "diag_exec_controller",
    deps = [
        "//diag/exec/factories:diag_exec_factories",
        "//communication-core/sockets:socket_ipc"
    ],
    srcs = ["exec_controller.cpp"],
    hdrs = ["exec_controller.hpp"],
    visibility = ["//visibility:public"],
)