cc_library(
    name = "controller",
    srcs = ["someip_controller.cc"],
    hdrs = [
        "i_someip_controller.h",
        "someip_controller.h",
    ],
    data = [],
    visibility = ["//ara/com:__subpackages__"],
    deps = [
        "//ara/com:com_controller",
        "//ara/com:com_log",
        "//ara/core:Result",
        "//ara/com/someip:someip_data"
    ],
)
