filegroup(
    name = "adc_test_data",
    srcs = [
        "t_1.json",
        "t_2.json",
        "t_3.json",
        "t_4.json",
        "t_5.json",
        "t_6.json",
        "t_7.json",
        "t_8.json",
        "t_9.json",
        "t_10.json",
        "t_11.json",
        "t_12.json"
        ],
    visibility = ["//visibility:public"],
)