load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "core",
    visibility = ["//visibility:public"],
    deps = [
        "//core/common:common_converter",
        "//core/common:common_types",
    ],
)
