cc_library(
    name = "i2c_controller",
    deps = [
        "//core/i2c:i2cdriver",
    ],
    srcs = ["i2c_controller.cpp"],
    hdrs = ["i2c_controller.h"],
    visibility = [
        "//apps:__subpackages__",
        ],
)