cc_library(
    name = "multicast_controller",
    srcs = ["multicast_controller.cc"],
    hdrs = ["multicast_controller.h"],
    visibility = ["//platform/common/someip_demon/code:__subpackages__"],
    deps = [
        "//ara/log",
        "//platform/common/someip_demon/code/common:udp_lib",
        "//platform/common/someip_demon/code/common/com:interface",
    ],
)
