cc_library(
    name = "did_job_lib",
    srcs = ["did_job.cc"],
    hdrs = ["did_job.h"],
    visibility = ["//visibility:public"],
    deps = ["//diag/jobs:job_common_lib"],
)

cc_library(
    name = "routine_control_job_lib",
    srcs = ["routine_control_job.cc"],
    hdrs = ["routine_control_job.h"],
    visibility = ["//visibility:public"],
    deps = ["//diag/jobs:job_common_lib"],
)

cc_library(
    name = "other_job_lib",
    srcs = ["other_job.cc"],
    hdrs = ["other_job.h"],
    visibility = ["//visibility:public"],
    deps = ["//diag/jobs:job_common_lib"],
)
