cc_binary(
    name = "test",
    deps = ["//core/application:simba_application"],
    srcs = ["main.cc",
    "test.cc",
    "test.h"],
    visibility = ["//deployment/apps/example:__subpackages__"],
)
