# cc_library(
#     name = "mock_someip_controller",
#     srcs = [
#         "mock_someip-controller.h",
#         ],
#     visibility = ["//visibility:public"],
#     deps=[
#         "@com_google_googletest//:gtest_main",
#         "//communication-core/someip-controller:someip_interface",
#     ],
#     testonly = True,
# )