# filegroup(
#     name = "Apps",
#     srcs = [
#         "//deployment/apps:Apps",
#         "//deployment/cpu:CPU_configs",
#         "//deployment/mw:MW_APPs",
#     ],
#     visibility = ["//visibility:public"],
# )
