cc_library(
    name = "dlt_data_types",
    hdrs = [
        "dlt_frame.h",
        "dlt_log_type.h",
        "dlt_string.h",
        "idlt_arg.h",
        "idlt_frame.h",
    ],
    visibility = ["//platform/common/logger/code:__subpackages__"],
    deps = [],
)
