cc_test(
    name = "data_structure",
    srcs = ["exec_structure.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//diag/exec/data:diag_exec_header",
        "@com_google_googletest//:gtest_main",
    ],
    size = "medium",
    testonly = True,
)