cc_test(
    name = "data_structure",
    srcs = ["exec_structure.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//diag/exec/data:diag_exec_header",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "diag_data_factory",
    srcs = ["exec_data_factory.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//diag/exec/factories:diag_exec_factories",
        "@com_google_googletest//:gtest_main",
    ],
)
