cc_library(
    name = "vin_did",
    hdrs = ["read_vin_did.h"],
    visibility = ["//apps/diag_ota:__subpackages__"],
    deps = [
        "//diag/jobs/skeleton:did_job_lib",
    ],
)

cc_library(
    name = "uptime_did",
    hdrs = ["uptime_did.h"],
    visibility = ["//apps/diag_ota:__subpackages__"],
    deps = [
        "//core/common:common_converter",
        "//diag/jobs/skeleton:did_job_lib",
    ],
)
