cc_library(
    name = "tinyNtp_header",
    deps = [
        "//communication-core/network-data:network_data_structure",
        "//communication-core/network-data:network_data_type"
    ],
    srcs = ["header.cpp"],
    hdrs = ["header.hpp"],
    visibility = ["//mw/timestamp_mw/ntp:__subpackages__"],
)