
# cc_test(
#     name = "temp_controller",
#     srcs = ["test_temp_controller.cc"],
#     visibility = ["//visibility:public"],
#     deps=[
#         "@com_google_googletest//:gtest_main",
#         "//mw/temp/controller:temp_controller_mw",
#         "//communication-core/sockets/mock:mock_socket",
#     ]
# )