sh_binary(
    name = "rename_sh",
    srcs = ["rename.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "flash_sh",
    srcs = ["flash.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "connect_tar_sh",
    srcs = ["connect_tar.sh"],
    visibility = ["//visibility:public"],
)
sh_binary(
    name = "docker_flash_sh",
    srcs = ["docker_flash.sh"],
    visibility = ["//visibility:public"],
)