cc_library(
    name = "csvdriver",
    deps = [],
    srcs = ["csvdriver.cc"],
    hdrs = [
        "csvdriver.h",
        "Icsvdriver.h",
        ],
    visibility = [
        "//apps/ec/logger_service:__subpackages__",
        "//core/csvdriver/mock:__subpackages__",
        "//core/test:__subpackages__",
    ],
)
