cc_library(
    name = "csvdriver",
    deps = [
        "//core/file:file_lib",
    ],
    srcs = ["csvdriver.cc"],
    hdrs = [
        "csvdriver.h",
        "Icsvdriver.h",
        ],
    visibility = ["//visibility:public"],
)
