# cc_binary(
#     name = "em",
#     srcs = [
#         "em_application.cc",
#         "em_application.h",
#         "main.cc",
#     ],
#     visibility = ["//deployment:__subpackages__"],
#     deps = [
#         "//core/application:simba_application",
#         "//mw/em/code/services/em:em_service",
#         "//mw/em/code/services/exec:exec_service",
#     ],
# )
