sh_binary(
    name = "ec_initialize",
    srcs = ["initialize.sh"],
    visibility = ["//visibility:public"],
    args = ["ec", "192.168.10.101"],
)

sh_binary(
    name = "fc_initialize",
    srcs = ["initialize.sh"],
    visibility = ["//visibility:public"],
    args = ["fc", "192.168.10.102"],
)
