cc_test(
    name = "csvdriver_test",
    srcs = ["test_csvdriver.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//apps/logger_service/csvdriver:csvdriver"
    ],
    visibility = ["//visibility:public"],
)
