cc_library(
    name = "i2cdriver",
    srcs = ["i2cdriver.cpp"],
    hdrs = ["i2cdriver.h"],
    deps = ["//core/common:common_types", "//core/results:results_lib"],
    visibility = ["//core:__subpackages__"],
)
