cc_test(
    name = "data_structure",
    srcs = ["test_data_hdr.cpp"],
    visibility = ["//visibility:public"],
    deps=[
        "@com_google_googletest//:gtest_main",
        "//diag/dtc/data:diag_dtc_data_structure"
    ]
)

cc_test(
    name = "data_factories",
    srcs = ["test_data_hdr.cpp"],
    visibility = ["//visibility:public"],
    deps=[
        "@com_google_googletest//:gtest_main",
        "//diag/dtc/data:diag_dtc_data_structure"
    ]
)