cc_library(
    name = "ntp_data_lib",
    deps = [
        "//communication-core/network-data:network_data_structure",
        "//communication-core/network-data:network_data_type",
    ],
    srcs = [
        "header.cpp",
    ],
    hdrs = [
        "header.hpp",
    ],
)