filegroup(
    name = "pca9685_test_data",
    srcs = [
        "basic.json",
        "c_t_1.json",
        "c_t_2.json",
        "c_t_3.json",
        "c_t_4.json",
        ],
    visibility = ["//visibility:public"],
)