cc_library(
    name = "i2cdriver",
    srcs = ["i2cdriver.cpp"],
    hdrs = [
        "i2cdriver.hpp",
        ],
    deps = [
        "//core/common:common_types",
    ],
    visibility = ["//core:__subpackages__",
    "//mw:__subpackages__",
    ],
)