cc_library(
    name = "ina219_controller",
    deps = [
        "//mw/i2c_service/controller:i2c_controller",
        "//core/json:simba_json",
    ],
    srcs = ["controller.cpp"],
    hdrs = [
        "controller.hpp",
        ],
    visibility = ["//visibility:public"],
)
