cc_library(
    name = "mock_csvdriver",
    srcs = ["mock_csvdriver.h"],
    visibility = ["//visibility:public"],
    deps=[
        "@com_google_googletest//:gtest_main",
        "//apps/logger_service/csvdriver:csvdriver",
    ],
    testonly = True,
)
