cc_library(
    name = "eeprom_config",
    deps = [
        "//mw/i2c_service/controller/24lc32at:controller"
    ],
    hdrs = ["cfg_manager.hpp"],
    visibility = [
        "//visibility:public",
    ],
)

