cc_library(
    name = "converter_lib",
    deps = ["//communication-core/network-data:network_data_type"],
    srcs = ["converter.cc"],
    hdrs = ["converter.h"],
    visibility = ["//mw/diag/dtc:__subpackages__"],
)