cc_library(
    name = "DatabaseLib",
    srcs = ["database.cc"],
    hdrs = [
        "Idatabase.h",
        "database.h",
        "database_element.h",
        "event_element.h",
        "method_element.h",
    ],
    visibility = ["//communication-core:__subpackages__"],
    deps = ["//core"],
)
