cc_library(
    name = "DatabaseLib",
    srcs = ["database.cc"],
    hdrs = [
        "Idatabase.h",
        "database.h",
        "database_element.h",
        "req_event_element.h",
        "event_element.h",
        "method_element.h",
        "net_interface_element.h",
        "service_element.h",
        "app_element.h"
    ],
    visibility = ["//communication-core:__subpackages__"],
    deps = ["//core"],
)
