# filegroup(
#     name = "CPU_configs",
#     srcs = [
#         "//deployment/cpu/ec:config",
#         "//deployment/cpu/pc:config",
#         "//deployment/cpu/fc:config",
#     ],
#     visibility = ["//deployment:__subpackages__"],
# )