cc_binary(
    name = "dlt",
    srcs = ["test_dlt.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//mw/logger/code/data:dlt_data_types",
    ],
    visibility = ["//visibility:public"],
)