cc_test(
    name = "test_routable_uds_service",
    srcs = ["test_routable_uds_service.cc"],
    features = ["test_target"],
    deps = [
        "//ara/com/socket/mock",
        "//ara/diag/routing",
        "//ara/diag/routing:routing_for_ut",
    ],
)
