# cc_library(
#     name = "mock_i2c",
#     srcs = [
#         "mock_i2cdriver.hpp",
#         ],
#     visibility = ["//visibility:public"],
#     deps=[
#         "@com_google_googletest//:gtest_main",
#         "//core/i2c:i2cdriver",
#     ],
#     testonly = True,
# )