
cc_library(
    name = "eeprom_hdr",
    srcs = [
        "eeprom_hdr.cpp",
        ],
    hdrs = [
        "eeprom_hdr.hpp",
        ],
    deps = [
        "//communication-core/network-data:network_data_structure",
        "//communication-core/network-data:network_data_type",
    ],
    visibility = [
        "//mw/i2c_service:__subpackages__",
        ],
)