cc_library(
    name = "simba_application",
    hdrs = [
        "Iapplication.h",
        "application_factory.h",
        "application_no_ipc.h",
        "parm.h",
    ],
    visibility = ["//core:__subpackages__"],
    deps = [
        "@com_json//:json",
        "//core/logger:console_logger",
    ],
)
