cc_library(
    name = "ptp_controller",
    deps = [
        "//ara/com/shm:shm_lib",
        "//ara/log",
    ],
    hdrs = [
        "ptp_controller.hpp",
    ],
    srcs = [
        "ptp_controller.cpp",
    ],
    visibility = ["//example_adaptive/ExampleApp/code/application:__subpackages__"],
)