load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "test",
    srcs = ["test.py","addition_method_parameters.py","temperature_msg.py"],
    imports = ["."],
    deps = [
        "//third_party/python/someipy/src:someipy_lib"
    ],
)

py_binary(
    name = "test2",
    srcs = ["test2.py","addition_method_parameters.py","temperature_msg.py"],
    imports = ["."],
    deps = [
        "//third_party/python/someipy/src:someipy_lib"
    ],
)
py_binary(
    name = "test3",
    srcs = ["test3.py","addition_method_parameters.py","temperature_msg.py"],
    imports = ["."],
    deps = [
        "//third_party/python/someipy/src:someipy_lib"
    ],
)