
load("//deployment/bazel:config_gen.bzl", "bs_someip_gen")


# bs_someip_gen(
#     name="config",
#     config_src = [":app_config"],
#     includes = ["//deployment:Apps"],
#     )
# filegroup(
#     name = "app_config",
#     srcs = ["app.json"],
#     visibility = ["//deployment/cpu/pc:__subpackages__"],
# )
