cc_library(
    name = "sys_time_change_lib",
    srcs = ["sys_time.cpp"],
    hdrs = ["sys_time.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/common:common_types",
    ],
)
