cc_library(
    name = "binary_file_lib",
    srcs = [
        "writer.cpp"
    ],
    hdrs = [
        "writer.hpp",
    ],
    visibility = [
        "//visibility:public",
        ],
    deps = [
        "@srp_platform//ara/log",
    ],
)
