load("//deployment/tools/ara:adaptive_application.bzl", "ara_runtime_lib")

ara_runtime_lib(
    name = "ara",
    model_src = ["//deployment/example_adaptive/ExampleApp:instance"],
    visibility = ["//example_adaptive/ExampleApp/code:__subpackages__"],
)