cc_library(
    name = "ntp_discovery",
    srcs = [
        "discovery_manager.cpp",
    ],
    hdrs = [
        "discovery_manager.hpp",
    ],
    deps = [
        "//core/common:condition_lib",
        "@srp_platform//ara/log",
    ],
    visibility = ["//visibility:public"],
)
