cc_library(
    name = "ntp_discovery",
    srcs = [
        "discovery_manager.cpp",
    ],
    hdrs = [
        "discovery_manager.hpp",
    ],
    deps = [
    ],
    visibility = ["//visibility:public"],
)