
cc_library(
    name = "diag_exec_header",
    deps = [
        "//communication-core/network-data:network_data_structure",
    ],
    srcs = ["exec_header.cpp"],
    hdrs = ["exec_header.hpp"],
    visibility = ["//visibility:public"],
)
