cc_library(
    name = "temp_reading_msg_factory",
    srcs = ["temp_reading_msg_factory.cpp"],
    hdrs = ["temp_reading_msg_factory.h"],

    visibility = [
        "//mw/temp:__subpackages__",
    ],
)