cc_library(
    name = "diag_dtc_msg_factory",
    srcs = ["dtc_msg_factory.cpp"],
    hdrs = ["dtc_msg_factory.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//core/results:results_lib",
        "//diag_dtc/data:diag_dtc_data_structure",
    ],
)
