cc_library(
    name = "mock_sys_time_changer",
    hdrs = [
        "mockTime.h"
        ],
    visibility = ["//visibility:public"],
    deps=[
        "@com_google_googletest//:gtest_main",
        "//core/time:sys_time_change_lib",
    ],
    testonly = True,
)
