cc_library(
    name = "gpio_hdr",
    srcs = [
        "header.cpp",
        "resHeader.cpp",
        ],
    hdrs = [
        "header.hpp",
        "resHeader.hpp"
        ],
    deps = [
        "//communication-core/network-data:network_data_structure",
        "//communication-core/network-data:network_data_type",
    ],
    visibility = ["//visibility:public"],
)