cc_library(
    name = "diag_controller",
    hdrs = ["diag_controller.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//diag/dtc/controller:diag_dtc_I_controller",
        "//diag/dtc/controller:diag_dtc_controller",
    ],
)
