name: Build deployments (BeagleBone config)

on:
  pull_request:
    types: [labeled, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: matiko42/simba_github_action:latest
    steps:
      - name: check lable
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8

      - name: Checkout Repository
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.PRIVATE_KEY_FOR_DEPLOY_KEY_IN_SUBMODULE }}
      - name: Cache Bazel data
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel-cache-cpu-${{ runner.os }}-${{ hashFiles('**/BUILD.bazel') }}
      - name: RM 1
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Starting built software for BeagleBone (EC)
          comment_tag: to_delete
      - name: Run build engine computer
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        run: |
            bazel build --config=bbb //deployment/cpu/ec:pkg
      - name: Add msg
        if: contains(steps.pr-labels.outputs.labels, 'check')
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
               Successfully built software for BeagleBone (EC)
      - name: Run build flight computer
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        run: |
            bazel build --config=bbb //deployment/cpu/fc:pkg
      - name: Add msg_2
        if: contains(steps.pr-labels.outputs.labels, 'check')
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
               Successfully built software for BeagleBone (FC)
          
  
  