name: Build deployments (BeagleBone config)

on:
  pull_request:
    types: [labeled, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - name: check lable
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8

      - name: Checkout Repository
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.PRIVATE_KEY_FOR_DEPLOY_KEY_IN_SUBMODULE }}
      - name: Cache bazel directories
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.cache/bazel/*
          key: ${{ runner.os }}-bazel-bbb-${{ hashFiles('**/lockfiles') }}
      - name: RM 1
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Starting built software for BeagleBone (EC)
          comment_tag: to_delete

      - name: Install bazel
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        run: |
          sudo apt install apt-transport-https curl gnupg
          sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
          sudo apt update
          sudo apt install g++-13 gcc-13
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel-5.4.1

      - name: Run build engine computer
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        run: |
            bazel build --config=bbb //deployment/cpu/ec:pkg
      - name: Add msg
        if: contains(steps.pr-labels.outputs.labels, 'check')
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
               Successfully built software for BeagleBone (EC)
      - name: Run build flight computer
        if: contains(steps.pr-labels.outputs.labels, 'check-bbb')
        run: |
            bazel build --config=bbb //deployment/cpu/fc:pkg
      - name: Add msg_2
        if: contains(steps.pr-labels.outputs.labels, 'check')
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
               Successfully built software for BeagleBone (FC)
          
  
  