---
name: Lint, build and test SRP
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:
jobs:
  cpplint:
    name: CppLint Check
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/simba-avionic/simba_avionics_dockers/docker-action:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run cpplint
        run: |
          /bin/bash ./tools/cpplint/cpplint.sh

  build-and-test:
    name: SRP Build & Test SRP
    needs: cpplint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/simba-avionic/simba_avionics_dockers/docker-action:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build & Test
        run: |
          bazel build --config=bbb-platform //deployment/cpu/ec:pkg //deployment/cpu/fc:pkg

          ./tools/ut/unittest.sh

          ./tools/build_all/build_all.sh
