name: Check UT

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: matiko42/simba_github_action:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache Bazel data
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/bazel
          key: bazel-cache-ut-${{ runner.os }}-${{ hashFiles('**/BUILD.bazel') }}
      # - name: Run ut
      #   run: |
      #     gcc --version
      #     bazel test  `bazel query 'kind(cc_.*, tests(//...))'`
  
  