name: Check UT

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: matiko42/simba_github_action:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run ut
        run: |
          gcc --version
          bazel test  `bazel query 'kind(cc_.*, tests(//...))'`
  
  