
cc_library(
    name = "eeprom_factory",
    srcs = [
        "eeprom_factory.cpp",
        ],
    hdrs = [
        "eeprom_factory.hpp",
        ],
    deps = [
        "//mw/i2c_service/eeprom/data:eeprom_hdr",
    ],
    visibility = [
        "//mw/i2c_service:__subpackages__",
        ],
)