cc_library(
    name = "IPC_Service",
    hdrs = ["sm_service.h"],
    visibility = ["//platform/common/em/code:__subpackages__"],
    deps = [
        "//deployment/platform/em:someip_lib",
        "//platform/common/em/code/services/em:em_service",
    ],
)
